export enum ServiceRequestStatus {
  OPEN = 'OPEN',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  CUSTOMER_CONFIRMATION_PENDING = 'CUSTOMER_CONFIRMATION_PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_CUSTOMER_CONFIRMATION = 'AWAITING_CUSTOMER_CONFIRMATION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  DISPUTED = 'DISPUTED',
}
