export enum ServiceRequestStatus {
  OPEN = 'OPEN',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  DISPUTED = 'DISPUTED',
}
